services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Base\:
        resource: '../../src/Base'
        exclude: '../../src/Base/Model/{DTO,Form,Entity,Enum}'